### ISSUE TITLE
UI improvement 2: Loading animation

### ISSUE THREAD

**Issue by priyo97** [bunnycodec/Weather_App#2]
For slow internet connection, the query result fetching and displaying might take some visible delay. During that time, there's a black page which might be misleading for users as they might not understand whether the app is not working or whether they did not perform the right actions to see the expected output.

**Comment by bunnycodec** [comment]
A loader has been added. 
Please check out and drop your valuable suggestion.

**Comment by priyo97** [comment]
Looks good. Fix accepted
